version: "3"
services:
  reverseproxy:
    build:
      context: ../udacity-c3-rproxy
    image: tazio/ulab-c3-rproxy:v1
  backend_user:
    build:
      context: ../udacity-c3-restapi-user
    image: tazio/ulab-c3-user:v1
  backend_feed:
    build:
      context: ../udacity-c3-restapi-feed  
    image: tazio/ulab-c3-feed:v1
  frontend:
    build:
      context: ../udacity-c3-frontend  
    image: tazio/ulab-c3-fe:v1
