apiVersion: apps/v1
kind: Deployment
metadata:
  name: rproxy
  labels:
    app: rproxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rproxy
    spec:
      containers:
      - name: rproxy
        image: tazio/ulab-c3-rproxy:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
    restartPolicy: Always
